package schema

import (
	"context"
	"database/sql"
	"flag"
	"log"
	"os"
	"strings"
	"testing"
	"time"

	_ "github.com/go-sql-driver/mysql"
	_ "github.com/jackc/pgx/v5/stdlib"
	_ "github.com/microsoft/go-mssqldb"
	_ "github.com/sijms/go-ora/v2"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

var (
	dbTests    *bool
	db         *sql.DB
	driverName string
)

func TestMain(m *testing.M) {
	dbTests = flag.Bool("db", false, "run database integration tests")
	flag.Parse()

	if *dbTests {
		setupDatabase()
	}

	code := m.Run()

	if *dbTests {
		if db != nil {
			db.Close()
		}
	}

	os.Exit(code)
}

func setupDatabase() {
	connStr, ok := os.LookupEnv("URL")
	if !ok {
		log.Fatal("missing URL env var")
	}

	driverName, ok = os.LookupEnv("DRIVER")
	if !ok {
		log.Fatal("missing DRIVER env var")
	}

	var err error
	for range 30 {
		db, err = sql.Open(driverName, connStr)
		if err == nil {
			err = db.Ping()
		}
		if err == nil {
			return
		}
		time.Sleep(time.Second)
	}

	log.Fatalf("connecting to database after retries: %v", err)
}

func skipIfNoDB(t *testing.T) {
	t.Helper()
	if !*dbTests {
		t.Skip("skipping database test (use -db flag to enable)")
	}
}

// schemaName returns the schema/database name to use for introspection.
func schemaName() string {
	switch driverName {
	case "pgx":
		return "public"
	case "mysql":
		return "defaultdb"
	case "mssql":
		return "dbo"
	case "oracle":
		return "system"
	default:
		return "public"
	}
}

// createTestSchema creates a small schema with PKs, FKs, and varied column
// types so we can exercise Inspect, SortTables, and Generate end-to-end.
func createTestSchema(t *testing.T, ctx context.Context) {
	t.Helper()

	var stmts []string
	switch driverName {
	case "pgx":
		stmts = []string{
			`CREATE TABLE IF NOT EXISTS schema_authors (
				id SERIAL PRIMARY KEY,
				name VARCHAR(255) NOT NULL,
				active BOOLEAN NOT NULL DEFAULT true,
				created_at TIMESTAMPTZ NOT NULL DEFAULT now()
			)`,
			`CREATE TABLE IF NOT EXISTS schema_books (
				id SERIAL PRIMARY KEY,
				title VARCHAR(255) NOT NULL,
				author_id INT NOT NULL REFERENCES schema_authors(id),
				price DECIMAL(10,2),
				published DATE
			)`,
		}
	case "mysql":
		stmts = []string{
			`CREATE TABLE IF NOT EXISTS schema_authors (
				id INT AUTO_INCREMENT PRIMARY KEY,
				name VARCHAR(255) NOT NULL,
				active BOOLEAN NOT NULL DEFAULT true,
				created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
			)`,
			`CREATE TABLE IF NOT EXISTS schema_books (
				id INT AUTO_INCREMENT PRIMARY KEY,
				title VARCHAR(255) NOT NULL,
				author_id INT NOT NULL,
				price DECIMAL(10,2),
				published DATE,
				FOREIGN KEY (author_id) REFERENCES schema_authors(id)
			)`,
		}
	case "mssql":
		stmts = []string{
			`IF OBJECT_ID('schema_books', 'U') IS NOT NULL DROP TABLE schema_books`,
			`IF OBJECT_ID('schema_authors', 'U') IS NOT NULL DROP TABLE schema_authors`,
			`CREATE TABLE schema_authors (
				id INT IDENTITY(1,1) PRIMARY KEY,
				name NVARCHAR(255) NOT NULL,
				active BIT NOT NULL DEFAULT 1,
				created_at DATETIME2 NOT NULL DEFAULT GETDATE()
			)`,
			`CREATE TABLE schema_books (
				id INT IDENTITY(1,1) PRIMARY KEY,
				title NVARCHAR(255) NOT NULL,
				author_id INT NOT NULL FOREIGN KEY REFERENCES schema_authors(id),
				price DECIMAL(10,2),
				published DATE
			)`,
		}
	case "oracle":
		stmts = []string{
			`BEGIN EXECUTE IMMEDIATE 'DROP TABLE schema_books CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;`,
			`BEGIN EXECUTE IMMEDIATE 'DROP TABLE schema_authors CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;`,
			`CREATE TABLE schema_authors (
				id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				name VARCHAR2(255) NOT NULL,
				active NUMBER(1) DEFAULT 1 NOT NULL,
				created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
			)`,
			`CREATE TABLE schema_books (
				id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				title VARCHAR2(255) NOT NULL,
				author_id NUMBER(10) NOT NULL REFERENCES schema_authors(id),
				price NUMBER(10,2),
				published DATE
			)`,
		}
	}

	for _, stmt := range stmts {
		_, err := db.ExecContext(ctx, stmt)
		require.NoError(t, err, "creating test schema: %s", stmt)
	}
}

// dropTestSchema removes the test tables.
func dropTestSchema(ctx context.Context) {
	switch driverName {
	case "oracle":
		db.ExecContext(ctx, `BEGIN EXECUTE IMMEDIATE 'DROP TABLE schema_books CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;`)
		db.ExecContext(ctx, `BEGIN EXECUTE IMMEDIATE 'DROP TABLE schema_authors CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;`)
	case "mssql":
		db.ExecContext(ctx, `IF OBJECT_ID('schema_books', 'U') IS NOT NULL DROP TABLE schema_books`)
		db.ExecContext(ctx, `IF OBJECT_ID('schema_authors', 'U') IS NOT NULL DROP TABLE schema_authors`)
	default:
		db.ExecContext(ctx, "DROP TABLE IF EXISTS schema_books")
		db.ExecContext(ctx, "DROP TABLE IF EXISTS schema_authors")
	}
}

func TestInspect(t *testing.T) {
	skipIfNoDB(t)

	ctx := context.Background()
	createTestSchema(t, ctx)
	t.Cleanup(func() { dropTestSchema(ctx) })

	tables, err := Inspect(ctx, db, driverName, schemaName())
	require.NoError(t, err)

	// Find our two test tables among whatever else may exist.
	var authors, books *Table
	for i := range tables {
		switch tables[i].Name {
		case "schema_authors":
			authors = &tables[i]
		case "schema_books":
			books = &tables[i]
		}
	}

	require.NotNil(t, authors, "schema_authors not found in Inspect results")
	require.NotNil(t, books, "schema_books not found in Inspect results")

	// Authors columns.
	t.Run("authors_columns", func(t *testing.T) {
		colNames := columnNames(authors.Columns)
		assert.Contains(t, colNames, "id")
		assert.Contains(t, colNames, "name")
		assert.Contains(t, colNames, "active")
		assert.Contains(t, colNames, "created_at")
	})

	// Authors PK.
	t.Run("authors_pk", func(t *testing.T) {
		idCol := findColumn(authors.Columns, "id")
		require.NotNil(t, idCol)
		assert.True(t, idCol.IsPK, "authors.id should be PK")
	})

	// Authors auto-generated column.
	t.Run("authors_generated", func(t *testing.T) {
		idCol := findColumn(authors.Columns, "id")
		require.NotNil(t, idCol)
		assert.True(t, idCol.IsGenerated, "authors.id should be auto-generated")
	})

	// Books FK.
	t.Run("books_fk", func(t *testing.T) {
		authorIDCol := findColumn(books.Columns, "author_id")
		require.NotNil(t, authorIDCol)
		assert.Equal(t, "schema_authors.id", authorIDCol.Ref)
	})

	// Books nullable column.
	t.Run("books_nullable", func(t *testing.T) {
		priceCol := findColumn(books.Columns, "price")
		require.NotNil(t, priceCol)
		assert.True(t, priceCol.IsNullable, "books.price should be nullable")
	})

	// CreateStmt populated.
	t.Run("create_stmt", func(t *testing.T) {
		assert.NotEmpty(t, authors.CreateStmt, "authors.CreateStmt should be populated")
		assert.NotEmpty(t, books.CreateStmt, "books.CreateStmt should be populated")
	})
}

func TestSortTablesIntegration(t *testing.T) {
	skipIfNoDB(t)

	ctx := context.Background()
	createTestSchema(t, ctx)
	t.Cleanup(func() { dropTestSchema(ctx) })

	tables, err := Inspect(ctx, db, driverName, schemaName())
	require.NoError(t, err)

	sorted, err := SortTables(tables)
	require.NoError(t, err)

	// authors must come before books (books depends on authors).
	idx := orderIndex(sorted)
	authorsIdx, authorsOK := idx["schema_authors"]
	booksIdx, booksOK := idx["schema_books"]
	require.True(t, authorsOK, "schema_authors not in sorted output")
	require.True(t, booksOK, "schema_books not in sorted output")
	assert.Less(t, authorsIdx, booksIdx, "schema_authors should sort before schema_books")
}

func TestGenerateIntegration(t *testing.T) {
	skipIfNoDB(t)

	ctx := context.Background()
	createTestSchema(t, ctx)
	t.Cleanup(func() { dropTestSchema(ctx) })

	tables, err := Inspect(ctx, db, driverName, schemaName())
	require.NoError(t, err)

	sorted, err := SortTables(tables)
	require.NoError(t, err)

	output := Generate(sorted, driverName)

	// Valid YAML.
	assert.True(t, len(output) > 0, "Generate produced empty output")
	assert.Contains(t, output, "globals:")
	assert.Contains(t, output, "up:")
	assert.Contains(t, output, "seed:")
	assert.Contains(t, output, "deseed:")
	assert.Contains(t, output, "down:")

	// Table names appear in the output.
	assert.Contains(t, output, "schema_authors")
	assert.Contains(t, output, "schema_books")

	// CreateStmt content appears in up section.
	for _, tbl := range sorted {
		if tbl.Name == "schema_authors" || tbl.Name == "schema_books" {
			// The DDL or parts of it should be in the output.
			assert.Contains(t, output, "create_"+tbl.Name)
		}
	}
}

func TestInspect_UnsupportedDriver(t *testing.T) {
	skipIfNoDB(t)

	_, err := Inspect(context.Background(), db, "sqlite", schemaName())
	require.Error(t, err)
	assert.Contains(t, err.Error(), "unsupported driver")
}

func columnNames(cols []Column) []string {
	names := make([]string, len(cols))
	for i, c := range cols {
		names[i] = c.Name
	}
	return names
}

func findColumn(cols []Column, name string) *Column {
	for i := range cols {
		if strings.EqualFold(cols[i].Name, name) {
			return &cols[i]
		}
	}
	return nil
}
