title: edg
description: A database workload runner driven by YAML configuration
url: https://codingconcepts.github.io
baseurl: /edg

theme: just-the-docs

logo: /assets/logo.png

color_scheme: dark

aux_links:
  GitHub: https://github.com/codingconcepts/edg

footer_content: >-
  edg is maintained by <a href="https://github.com/codingconcepts">codingconcepts</a>.

search_enabled: true
search.heading_level: 3

nav_sort: case_insensitive

back_to_top: true
back_to_top_text: Back to top

sass:
  quiet_deps: true

exclude:
  - Gemfile
  - Gemfile.lock
