package pkg

import (
	"encoding/json"
	"errors"
	"fmt"
	"math/rand/v2"
	"strings"
	"time"

	"github.com/brianvoe/gofakeit/v7"
	"github.com/codingconcepts/edg/pkg/random"
)

func gen(s string) any {
	val, err := gofakeit.Generate(wrap(s))
	if err != nil {
		return nil
	}
	return val
}

// genBatch generates totalCount values using the given gofakeit pattern,
// split into groups of batchSize. Returns [][]any where each inner slice
// contains a comma-separated string of generated values, acting as a
// batch driver for GenerateArgs.
func genBatch(totalCount, batchSize any, pattern string) [][]any {
	total := toInt(totalCount)
	size := toInt(batchSize)
	if size <= 0 {
		size = total
	}
	batches := (total + size - 1) / size
	result := make([][]any, batches)
	for i := range batches {
		n := size
		if remaining := total - i*size; remaining < size {
			n = remaining
		}
		parts := make([]string, n)
		for j := range n {
			val := gen(pattern)
			if val != nil {
				parts[j] = fmt.Sprintf("%v", val)
			}
		}
		result[i] = []any{strings.Join(parts, ",")}
	}
	return result
}

func genUUIDv1() string { return random.UUIDv1() }
func genUUIDv4() string { return random.UUIDv4() }
func genUUIDv6() string { return random.UUIDv6() }
func genUUIDv7() string { return random.UUIDv7() }

// floatRand generates a random float64 in [min, max] rounded to the
// given number of decimal places.
//
//	uniform_f(min, max, precision)
func floatRand(min, max, precision any) float64 {
	return random.Float(toFloat(min), toFloat(max), toInt(precision))
}

// uniformRand generates a uniform random float64 in [min, max].
//
//	uniform(min, max)
func uniformRand(min, max any) float64 {
	return random.Uniform(toFloat(min), toFloat(max))
}

// zipfRand generates a Zipfian-distributed random integer in [0, max].
// Parameters s (> 1) and v (>= 1) control the distribution shape.
//
//	zipf(s, v, max)
func zipfRand(s, v, imax any) int {
	return random.Zipf(toFloat(s), toFloat(v), toInt(imax))
}

// genRegex generates a random string matching the given regex pattern.
//
//	regex('[A-Z]{3}-[0-9]{4}')
func genRegex(pattern string) string {
	return random.Regex(pattern)
}

// jsonObj builds a JSON object string from key-value pair arguments.
//
//	json_obj('key1', val1, 'key2', val2)
func jsonObj(pairs ...any) (string, error) {
	if len(pairs)%2 != 0 {
		return "", errors.New("json_obj requires an even number of arguments (key-value pairs)")
	}

	m := make(map[string]any, len(pairs)/2)
	for i := 0; i < len(pairs); i += 2 {
		m[fmt.Sprintf("%v", pairs[i])] = pairs[i+1]
	}

	b, err := json.Marshal(m)
	if err != nil {
		return "", err
	}
	return string(b), nil
}

// jsonArr builds a JSON array string of N random values generated by
// the given gofakeit pattern, where N is in [minN, maxN].
//
//	json_arr(1, 5, 'email')
func jsonArr(minN, maxN any, pattern string) (string, error) {
	lo := toInt(minN)
	hi := toInt(maxN)
	n := lo + rand.IntN(hi-lo+1)

	values := make([]any, n)
	for i := range n {
		values[i] = gen(pattern)
	}

	b, err := json.Marshal(values)
	if err != nil {
		return "", err
	}
	return string(b), nil
}

// genPoint generates a random geographic point within radiusKM of
// (lat, lon) and returns a map with "lat" and "lon" keys.
//
//	point(51.5, -0.1, 10).lat
func genPoint(lat, lon, radiusKM any) map[string]any {
	newLat, newLon := random.Point(toFloat(lat), toFloat(lon), toFloat(radiusKM))
	return map[string]any{
		"lat": newLat,
		"lon": newLon,
	}
}

// genPointWKT generates a random geographic point within radiusKM of
// (lat, lon) and returns a WKT string: "POINT(lon lat)".
//
//	point_wkt(51.5, -0.1, 10)
func genPointWKT(lat, lon, radiusKM any) string {
	newLat, newLon := random.Point(toFloat(lat), toFloat(lon), toFloat(radiusKM))
	return fmt.Sprintf("POINT(%f %f)", newLon, newLat)
}

// randTimestamp generates a random timestamp between min and max,
// both in RFC3339 format. Returns the result in RFC3339.
//
//	timestamp('2020-01-01T00:00:00Z', '2025-01-01T00:00:00Z')
func randTimestamp(min, max string) string {
	minT, err := time.Parse(time.RFC3339, min)
	if err != nil {
		return ""
	}
	maxT, err := time.Parse(time.RFC3339, max)
	if err != nil {
		return ""
	}
	return random.Timestamp(minT, maxT).UTC().Format(time.RFC3339)
}

// randDuration generates a random duration between min and max,
// both as Go duration strings (e.g. "1h", "30m").
//
//	duration('1h', '24h')
func randDuration(min, max string) string {
	minD, err := time.ParseDuration(min)
	if err != nil {
		return ""
	}
	maxD, err := time.ParseDuration(max)
	if err != nil {
		return ""
	}
	return random.Duration(minD, maxD).String()
}

// dateRand generates a random timestamp between min and max (RFC3339)
// and formats the result using the given Go time format string.
//
//	date('2006-01-02', '2020-01-01T00:00:00Z', '2025-01-01T00:00:00Z')
func dateRand(format, min, max string) string {
	minT, err := time.Parse(time.RFC3339, min)
	if err != nil {
		return ""
	}
	maxT, err := time.Parse(time.RFC3339, max)
	if err != nil {
		return ""
	}
	return random.Timestamp(minT, maxT).UTC().Format(format)
}

// dateOffset returns the current time offset by the given Go duration
// string, formatted as RFC3339.
//
//	date_offset('-72h')
//	date_offset('30m')
func dateOffset(duration string) string {
	d, err := time.ParseDuration(duration)
	if err != nil {
		return ""
	}
	return time.Now().Add(d).UTC().Format(time.RFC3339)
}

// expRand returns an exponentially-distributed random float in [min, max],
// rounded to 0 decimal places by default.
//
//	exp(rate, min, max)
func expRand(rawRate, rawMin, rawMax any) float64 {
	return random.Exp(toFloat(rawRate), toFloat(rawMin), toFloat(rawMax))
}

// expRandF returns an exponentially-distributed random float in [min, max],
// rounded to the given number of decimal places.
//
//	exp_f(rate, min, max, precision)
func expRandF(rawRate, rawMin, rawMax, rawPrecision any) float64 {
	return random.Exp(toFloat(rawRate), toFloat(rawMin), toFloat(rawMax), toInt(rawPrecision))
}

// lognormRand returns a log-normally-distributed random float in [min, max],
// rounded to 0 decimal places by default.
//
//	lognorm(mu, sigma, min, max)
func lognormRand(rawMu, rawSigma, rawMin, rawMax any) float64 {
	return random.LogNorm(toFloat(rawMu), toFloat(rawSigma), toFloat(rawMin), toFloat(rawMax))
}

// lognormRandF returns a log-normally-distributed random float in [min, max],
// rounded to the given number of decimal places.
//
//	lognorm_f(mu, sigma, min, max, precision)
func lognormRandF(rawMu, rawSigma, rawMin, rawMax, rawPrecision any) float64 {
	return random.LogNorm(toFloat(rawMu), toFloat(rawSigma), toFloat(rawMin), toFloat(rawMax), toInt(rawPrecision))
}

// genBytes generates n random bytes as a hex-encoded string prefixed
// with \x, matching the CockroachDB/PostgreSQL BYTES literal format.
//
//	bytes(16)
func genBytes(n any) string {
	return random.Bytes(toInt(n))
}

// genBit generates a random fixed-length bit string of exactly n bits.
//
//	bit(8)
func genBit(n any) string {
	return random.Bit(toInt(n))
}

// genVarBit generates a random variable-length bit string of 1 to n bits.
//
//	varbit(16)
func genVarBit(n any) string {
	return random.VarBit(toInt(n))
}

// genInet generates a random IP address within the given CIDR block.
// Supports both IPv4 and IPv6.
//
//	inet('192.168.1.0/24')
//	inet('fd00::/64')
func genInet(cidr string) (string, error) {
	return random.Inet(cidr)
}

// genArray generates a CockroachDB/PostgreSQL array literal with a
// random number of elements in [min, max], each produced by the given
// gofakeit pattern.
//
//	array(2, 5, 'intrange[1,100]')
func genArray(minN, maxN any, pattern string) string {
	lo := toInt(minN)
	hi := toInt(maxN)
	n := lo + rand.IntN(hi-lo+1)

	parts := make([]string, n)
	for i := range n {
		v := gen(pattern)
		if v != nil {
			parts[i] = fmt.Sprintf("%v", v)
		}
	}

	return "{" + strings.Join(parts, ",") + "}"
}

// genTime generates a random time of day between min and max (HH:MM:SS).
//
//	time('08:00:00', '17:30:00')
func genTime(minStr, maxStr string) (string, error) {
	return random.TimeOfDay(minStr, maxStr)
}

// genTimez generates a random time of day between min and max (HH:MM:SS)
// with a +00:00 timezone suffix, for use with TIMETZ columns.
//
//	timez('08:00:00', '17:30:00')
func genTimez(minStr, maxStr string) (string, error) {
	t, err := random.TimeOfDay(minStr, maxStr)
	if err != nil {
		return "", err
	}
	return t + "+00:00", nil
}
